# reply-api（reply.api）
@gateway = http://127.0.0.1:8888
@adminUsername = admin
@adminPassword = admin123
@accessToken =
@id = 1
@screenplayId = 1
@actId = 1
@sceneId = 1
@frameId = 1

### BEGIN GENERATED

### @name login
POST {{gateway}}/api/auth/login
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}

> {%
  client.global.set("accessToken", response.body.data.access_token);
%}

### @name ping
GET {{gateway}}/api/reply/ping
Accept: application/json

### @name listComments
GET {{gateway}}/api/reply/screenplays/{{screenplay_id}}/comments?parent_id=1&page=1&page_size=20
Authorization: Bearer {{accessToken}}
Accept: application/json

### @name createComment
POST {{gateway}}/api/reply/screenplays/{{screenplay_id}}/comments
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "content": "example"
}
### @name updateComment
PUT {{gateway}}/api/reply/comments/{{id}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "content": "example"
}
### @name deleteComment
DELETE {{gateway}}/api/reply/comments/{{id}}
Authorization: Bearer {{accessToken}}
Accept: application/json

### END GENERATED
