# auth-api（auth.api）
@gateway = http://127.0.0.1:8888
@adminUsername = admin
@adminPassword = admin123
@accessToken =
@id = 1
@screenplayId = 1
@actId = 1
@sceneId = 1
@frameId = 1

### BEGIN GENERATED

### @name ping
GET {{gateway}}/api/auth/ping
Accept: application/json

### @name login
POST {{gateway}}/api/auth/login
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}
### @name register
POST {{gateway}}/api/auth/register
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}
### END GENERATED
