# auth-api（auth.api）
# 公开：POST /login、POST /register
@gateway = http://192.168.110.167:8888/
@adminUsername = admin
@adminPassword = admin123
@demoUsername = demo_user
@demoPassword = demo_pass_123


### BEGIN GENERATED

### @name ping
GET {{gateway}}/api/auth/ping
Accept: application/json

### @name login
POST {{gateway}}/api/auth/login
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}
### @name register
POST {{gateway}}/api/auth/register
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}
### END GENERATED




